### ISSUE TITLE
canvas setup race condition

### ISSUE THREAD

**Issue by mootootwo** [mootootwo/lox#1]
Rendering the canvas can begin before ctx is properly defined.

```
   render(){
        ctx.clearRect(0,0,canvas.width,canvas.height); // clear screen each frame
```

line number from part-3.. maybe different in other parts.  see snip above
```
engine.js:25 Uncaught ReferenceError: ctx is not defined
    at render (engine.js:25:9)
```

**Comment by mootootwo** [comment]
can add a wait state before attempting to invoke `render()` but should address this with better game-loop implementation

**Comment by mootootwo** [comment]
Resolved this for parts 2-5.  issue may not be present in parts 0 and 1, they have a simpler more serial screen setup process.

**Comment by mootootwo** [comment]
race condition still exists, promise does not always work as intended:

> Uncaught (in promise) ReferenceError: ctx is not defined
>     at render (engine.js:24:9)
> 

`ctx.clearRect(0,0,canvas.width,canvas.height); // clear screen each frame`
